#!/usr/bin/env bash
# Murmur Radio v1 -- fixed real playlist builder (Phase 3 proof-of-concept).
#
# Renders a small, hand-picked set of real ambient/pad presets through the
# real DSP engine (murmur-render), then crossfades them together into one
# continuous, seamless-loop MP3 with ffmpeg's `acrossfade` filter. The
# result is what murmur-radio.service (see radio/README.md) loops forever
# into Icecast -- this script is the offline "build" step, not something
# that runs inside the always-on service itself (rendering is real DSP
# work; looping an already-built file is cheap).
#
# Requires murmur-render already built (PW8_BUILD_TOOLS=ON) and ffmpeg on
# PATH. Real IMPORTANT gotcha this script's callers must know: murmur-render
# resolves every patch's relative paths (wavetableId, etc.) against its own
# working directory, so this script always shells out from REPO_ROOT --
# same reason mcp_server/render.py does the same thing.
#
# Usage: radio/build_playlist.sh <repo_root> <output_dir>
#   e.g. radio/build_playlist.sh /root/murmur-render-check /root/murmur-radio

set -euo pipefail

REPO_ROOT="${1:?Usage: build_playlist.sh <repo_root> <output_dir>}"
OUT_DIR="${2:?Usage: build_playlist.sh <repo_root> <output_dir>}"
RENDERER="${REPO_ROOT}/build/render-check/tools/murmur-render"

if [[ ! -x "$RENDERER" ]]; then
  echo "murmur-render not found/executable at $RENDERER -- build it first:" >&2
  echo "  cmake -S . -B build/render-check -G Ninja -DCMAKE_BUILD_TYPE=Release -DPW8_BUILD_TESTS=OFF -DPW8_BUILD_TOOLS=ON" >&2
  echo "  cmake --build build/render-check -j2 --target murmur-render" >&2
  exit 1
fi

# Real v2 playlist -- the original 3 hand-picked factory/showcase ambient
# presets, plus 6 real patches generated by the actual Cognitive Patch
# Agent (radio/generated/*.murmur, radio/generate_patches.md documents
# how -- same murmurPatchAgent.ts code path production /account uses, real
# Claude Sonnet 4.5 calls, ~$0.06 total). One 7th agent-generated patch
# (resonator-engine "RESONANT DRIFT") was dropped after real-render
# verification showed near-total silence (peak ~3e-5) on this exact MIDI
# -- a real DSP edge case, not shipped. "Agentic" *next-track selection*
# (per the plan) is still out of scope for this pass -- this is agentic
# *content generation* feeding a still-fixed playlist, prove that layer
# works before automating selection too.
declare -a PATCHES=(
  "content/presets/aurora-pad.murmur:content/test_midi/pad-chords.mid:01-aurora-pad"
  "content/presets/halcyon-pad.murmur:content/test_midi/tide_pad.mid:02-halcyon-pad"
  "content/presets/factory/Ambient/04-fathomless-drift.murmur:content/test_midi/bloom_pad.mid:03-fathomless-drift"
  "radio/generated/murmur-warm-drift-pad-3357703586.murmur:content/test_midi/dune-chords.mid:04-warm-drift-pad"
  "radio/generated/murmur-dark-drift-2984687883.murmur:content/test_midi/tide_pad.mid:05-dark-drift"
  "radio/generated/murmur-crystal-shimmer-wash-3247907687.murmur:content/test_midi/bloom_pad.mid:06-crystal-shimmer-wash"
  "radio/generated/murmur-airy-granular-drift-695748874.murmur:content/test_midi/pad-chords.mid:07-airy-granular-drift"
  "radio/generated/murmur-warm-breath-pad-3313946916.murmur:content/test_midi/demo-lfo-wobble.mid:08-warm-breath-pad"
  "radio/generated/murmur-distant-bell-drift-1582552353.murmur:content/test_midi/single-note.mid:09-distant-bell-drift"
)

mkdir -p "${OUT_DIR}/renders"
cd "$REPO_ROOT"

WAVS=()
for entry in "${PATCHES[@]}"; do
  IFS=':' read -r patch midi label <<< "$entry"
  out="${OUT_DIR}/renders/${label}.wav"
  echo "Rendering ${label} (${patch})..."
  "$RENDERER" --patch "$patch" --midi "$midi" --output "$out" --duration 45 --release-tail 3
  WAVS+=("$out")
done

# 4-second triangular crossfades, chained pairwise (ffmpeg's acrossfade only
# takes two inputs at a time) -- real overlap, not a hard cut, matching
# "crossfade between different arrangements" from the original ask. Built
# dynamically so the playlist length isn't hardcoded to 3 anymore.
echo "Crossfading ${#WAVS[@]} renders into ${OUT_DIR}/playlist.mp3..."

ffmpeg_inputs=()
for w in "${WAVS[@]}"; do
  ffmpeg_inputs+=(-i "$w")
done

filter=""
prev="[0]"
for ((i = 1; i < ${#WAVS[@]}; i++)); do
  next_label="[a$(printf '%02d' "$i")]"
  if (( i == ${#WAVS[@]} - 1 )); then
    next_label="[out]"
  fi
  filter+="${prev}[${i}]acrossfade=d=4:c1=tri:c2=tri${next_label};"
  prev="$next_label"
done
filter="${filter%;}"

ffmpeg -y \
  "${ffmpeg_inputs[@]}" \
  -filter_complex "$filter" \
  -map "[out]" -ar 44100 -c:a libmp3lame -b:a 192k "${OUT_DIR}/playlist.mp3"

echo "Done: ${OUT_DIR}/playlist.mp3"
