#!/usr/bin/env bash
# Murmur Radio v1 -- fixed real playlist builder (Phase 3 proof-of-concept).
#
# Renders a small, hand-picked set of real ambient/pad presets through the
# real DSP engine (murmur-render), then crossfades them together into one
# continuous, seamless-loop MP3 with ffmpeg's `acrossfade` filter. The
# result is what murmur-radio.service (see radio/README.md) loops forever
# into Icecast -- this script is the offline "build" step, not something
# that runs inside the always-on service itself (rendering is real DSP
# work; looping an already-built file is cheap).
#
# Requires murmur-render already built (PW8_BUILD_TOOLS=ON) and ffmpeg on
# PATH. Real IMPORTANT gotcha this script's callers must know: murmur-render
# resolves every patch's relative paths (wavetableId, etc.) against its own
# working directory, so this script always shells out from REPO_ROOT --
# same reason mcp_server/render.py does the same thing.
#
# Usage: radio/build_playlist.sh <repo_root> <output_dir>
#   e.g. radio/build_playlist.sh /root/murmur-render-check /root/murmur-radio

set -euo pipefail

REPO_ROOT="${1:?Usage: build_playlist.sh <repo_root> <output_dir>}"
OUT_DIR="${2:?Usage: build_playlist.sh <repo_root> <output_dir>}"
RENDERER="${REPO_ROOT}/build/render-check/tools/murmur-render"

if [[ ! -x "$RENDERER" ]]; then
  echo "murmur-render not found/executable at $RENDERER -- build it first:" >&2
  echo "  cmake -S . -B build/render-check -G Ninja -DCMAKE_BUILD_TYPE=Release -DPW8_BUILD_TESTS=OFF -DPW8_BUILD_TOOLS=ON" >&2
  echo "  cmake --build build/render-check -j2 --target murmur-render" >&2
  exit 1
fi

# Real v3 playlist -- 3 hand-picked factory/showcase ambient presets, plus
# 28 real patches generated by the actual Cognitive Patch Agent across two
# batches (radio/generated/*.murmur; generation script is murmur-web's
# scripts/generate-radio-patches.ts -- same murmurPatchAgent.ts code path
# production /account uses, real Claude Sonnet 4.5 calls, ~$0.30 total
# across both batches). That script real-render-verifies every patch
# before keeping it (a quick murmur-render pass, checks peak against a
# silence threshold) -- 3 agent-generated patches were dropped across the
# two batches, all resonator-engine ("RESONANT DRIFT", "CALM STRING
# DRIFT", "DEEP BOW RESONANCE"), all measured near-total silence (peak
# ~3e-5 to ~8e-5) despite being structurally valid JSON. Consistent enough
# across 3 independent generations to flag as a real, repeatable engine
# issue worth a dedicated look someday -- not investigated further here,
# just consistently caught and never shipped. "Agentic" *next-track
# selection* (per the plan) is still out of scope for this pass -- this is
# agentic *content generation* feeding a still-fixed playlist, prove that
# layer works before automating selection too.
declare -a PATCHES=(
  "content/presets/aurora-pad.murmur:content/test_midi/pad-chords.mid:01-aurora-pad"
  "content/presets/halcyon-pad.murmur:content/test_midi/tide_pad.mid:02-halcyon-pad"
  "content/presets/factory/Ambient/04-fathomless-drift.murmur:content/test_midi/bloom_pad.mid:03-fathomless-drift"
  "radio/generated/murmur-warm-drift-pad-3357703586.murmur:content/test_midi/dune-chords.mid:04-warm-drift-pad"
  "radio/generated/murmur-dark-drift-2984687883.murmur:content/test_midi/tide_pad.mid:05-dark-drift"
  "radio/generated/murmur-crystal-shimmer-wash-3247907687.murmur:content/test_midi/bloom_pad.mid:06-crystal-shimmer-wash"
  "radio/generated/murmur-airy-granular-drift-695748874.murmur:content/test_midi/pad-chords.mid:07-airy-granular-drift"
  "radio/generated/murmur-warm-breath-pad-3313946916.murmur:content/test_midi/demo-lfo-wobble.mid:08-warm-breath-pad"
  "radio/generated/murmur-distant-bell-drift-1582552353.murmur:content/test_midi/single-note.mid:09-distant-bell-drift"
  "radio/generated/murmur-airy-grain-drift-2142700280.murmur:content/test_midi/pad-chords.mid:10-airy-grain-drift"
  "radio/generated/murmur-calm-wind-pad-30146534.murmur:content/test_midi/tide_pad.mid:11-calm-wind-pad"
  "radio/generated/murmur-cinematic-strings-492861825.murmur:content/test_midi/bloom_pad.mid:12-cinematic-strings"
  "radio/generated/murmur-crystal-shimmer-wash-2720738708.murmur:content/test_midi/dune-chords.mid:13-crystal-shimmer-wash-2"
  "radio/generated/murmur-crystal-wash-evolve-981984344.murmur:content/test_midi/demo-lfo-wobble.mid:14-crystal-wash-evolve"
  "radio/generated/murmur-dark-cinematic-drift-1412444436.murmur:content/test_midi/single-note.mid:15-dark-cinematic-drift"
  "radio/generated/murmur-dark-void-drift-3493857767.murmur:content/test_midi/pad-chords.mid:16-dark-void-drift"
  "radio/generated/murmur-deep-void-shimmer-2828523926.murmur:content/test_midi/tide_pad.mid:17-deep-void-shimmer"
  "radio/generated/murmur-distant-choir-pad-2489942795.murmur:content/test_midi/bloom_pad.mid:18-distant-choir-pad"
  "radio/generated/murmur-gentle-triangle-pad-3265396137.murmur:content/test_midi/dune-chords.mid:19-gentle-triangle-pad"
  "radio/generated/murmur-glacial-phase-476423523.murmur:content/test_midi/demo-lfo-wobble.mid:20-glacial-phase"
  "radio/generated/murmur-glacial-spectrum-1079468068.murmur:content/test_midi/single-note.mid:21-glacial-spectrum"
  "radio/generated/murmur-glass-shimmer-1704469132.murmur:content/test_midi/pad-chords.mid:22-glass-shimmer"
  "radio/generated/murmur-hazy-warmth-2143544380.murmur:content/test_midi/tide_pad.mid:23-hazy-warmth"
  "radio/generated/murmur-rain-on-glass-3618789390.murmur:content/test_midi/bloom_pad.mid:24-rain-on-glass"
  "radio/generated/murmur-soft-bell-chime-2433237892.murmur:content/test_midi/dune-chords.mid:25-soft-bell-chime"
  "radio/generated/murmur-soft-ep-chorus-1757860482.murmur:content/test_midi/demo-lfo-wobble.mid:26-soft-ep-chorus"
  "radio/generated/murmur-vintage-saw-pad-2375792245.murmur:content/test_midi/single-note.mid:27-vintage-saw-pad"
  "radio/generated/murmur-warm-breath-pad-3906066371.murmur:content/test_midi/pad-chords.mid:28-warm-breath-pad-2"
  "radio/generated/murmur-warm-drift-pad-3298602939.murmur:content/test_midi/tide_pad.mid:29-warm-drift-pad-2"
  "radio/generated/murmur-warm-organ-drone-1750320090.murmur:content/test_midi/bloom_pad.mid:30-warm-organ-drone"
  "radio/generated/murmur-warped-memory-3214856922.murmur:content/test_midi/dune-chords.mid:31-warped-memory"
)

mkdir -p "${OUT_DIR}/renders"
cd "$REPO_ROOT"

WAVS=()
for entry in "${PATCHES[@]}"; do
  IFS=':' read -r patch midi label <<< "$entry"
  out="${OUT_DIR}/renders/${label}.wav"
  echo "Rendering ${label} (${patch})..."
  "$RENDERER" --patch "$patch" --midi "$midi" --output "$out" --duration 45 --release-tail 3
  WAVS+=("$out")
done

# 4-second triangular crossfades, chained pairwise (ffmpeg's acrossfade only
# takes two inputs at a time) -- real overlap, not a hard cut, matching
# "crossfade between different arrangements" from the original ask. Built
# dynamically so the playlist length isn't hardcoded to 3 anymore.
echo "Crossfading ${#WAVS[@]} renders into ${OUT_DIR}/playlist.mp3..."

ffmpeg_inputs=()
for w in "${WAVS[@]}"; do
  ffmpeg_inputs+=(-i "$w")
done

filter=""
prev="[0]"
for ((i = 1; i < ${#WAVS[@]}; i++)); do
  next_label="[a$(printf '%02d' "$i")]"
  if (( i == ${#WAVS[@]} - 1 )); then
    next_label="[out]"
  fi
  filter+="${prev}[${i}]acrossfade=d=4:c1=tri:c2=tri${next_label};"
  prev="$next_label"
done
filter="${filter%;}"

ffmpeg -y \
  "${ffmpeg_inputs[@]}" \
  -filter_complex "$filter" \
  -map "[out]" -ar 44100 -c:a libmp3lame -b:a 192k "${OUT_DIR}/playlist.mp3"

echo "Done: ${OUT_DIR}/playlist.mp3"
